markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : FIREICE
production_url : http://aowcan.com
description: "aowcan's blog about anything he interested"
disqus_shortname: aowcanblog
analytics: UA-37710507-1
author :
  name : Hui Chen
  github : chzju
  email: me@aowcan.com
